#!/usr/bin/env bash
# Render .claude/skills/ from the harness-neutral canon under .agents/skills/.
#
# Every canonical skill becomes a real directory under .claude/skills/ — no
# symlinks, because a plugin install copies the tree and does not promise to
# keep links. SKILL.md is the canon with a generated-file banner and, when
# .claude/skill-models.json names the skill, `model:` (and `context: fork`)
# injected into the frontmatter. Every other file in the skill is copied as is.
#
#   scripts/skills/sync-claude-skills.sh          # write
#   scripts/skills/sync-claude-skills.sh --check  # exit 1 if anything is stale
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"; cd "$ROOT"
CANON=.agents/skills; OUT=.claude/skills; MANIFEST=.claude/skill-models.json
check=false; [ "${1:-}" = --check ] && check=true
[ -f "$MANIFEST" ] || { echo "missing $MANIFEST" >&2; exit 2; }
command -v jq >/dev/null || { echo "need jq" >&2; exit 2; }

render() { # name model fork -> stdout
  local src="$CANON/$1/SKILL.md" model="$2" fork="$3"
  awk -v model="$model" -v fork="$fork" -v name="$1" '
    NR==1 && $0=="---" { infm=1; print; next }
    infm && $0=="---" {
      print "# Generated by scripts/skills/sync-claude-skills.sh from .agents/skills/" name "/SKILL.md;"
      print "# edit that file and .claude/skill-models.json, never this copy."
      if (model != "") print "model: " model
      if (fork == "true") print "context: fork"
      infm=0
    }
    { print }' "$src"
}

# render one skill into a staging dir, then compare or move it into place
stage="$(mktemp -d)"; trap 'rm -rf "$stage"' EXIT
stale=()
for dir in "$CANON"/*/; do
  name="$(basename "$dir")"; dst="$OUT/$name"; tmp="$stage/$name"
  model="$(jq -r --arg n "$name" '.[$n].model // empty' "$MANIFEST")"
  fork="$(jq -r --arg n "$name" '.[$n].fork // false' "$MANIFEST")"
  mkdir -p "$tmp"
  render "$name" "$model" "$fork" > "$tmp/SKILL.md"
  # everything but SKILL.md is copied verbatim (scripts, evals, references)
  (cd "$dir" && find . -mindepth 1 -not -name SKILL.md -not -path './evals/results*' | while read -r p; do
     if [ -d "$p" ]; then mkdir -p "$tmp/$p"; else cp -p "$p" "$tmp/$p"; fi; done)
  if [ -d "$dst" ] && diff -rq "$tmp" "$dst" >/dev/null 2>&1; then continue; fi
  stale+=("$name"); $check && continue
  rm -rf "$dst"; mkdir -p "$OUT"; cp -R "$tmp" "$dst"
done
# a rendered skill with no canonical twin is a leftover
for dst in "$OUT"/*/; do
  [ -d "$dst" ] || continue
  name="$(basename "$dst")"
  [ -d "$CANON/$name" ] && continue
  stale+=("$name (remove)"); $check && continue
  rm -rf "$dst"
done
# manifest entries with no canonical skill are a typo
for n in $(jq -r 'keys[]' "$MANIFEST"); do [ -d "$CANON/$n" ] || { echo "manifest names $n but $CANON/$n does not exist" >&2; exit 2; }; done
if $check; then
  [ "${#stale[@]}" -eq 0 ] && exit 0
  printf 'stale .claude/skills copy: %s\n' "${stale[@]}" >&2
  echo "run scripts/skills/sync-claude-skills.sh" >&2; exit 1
fi
[ "${#stale[@]}" -eq 0 ] && echo "up to date" || printf 'synced %s\n' "${stale[@]}"
