#!/usr/bin/env bash
# Render the harness rosters from the canonical, harness-neutral agents under
# .agents/agents/. Same idea as scripts/skills/sync-claude-skills.sh.
#
# .agents/agent-manifest.json maps agent -> harness -> frontmatter keys to
# inject (tools, model). A harness with no entry for an agent does not get
# that file; a file in a harness dir with no canonical twin is left alone.
#
#   scripts/agents/sync-agents.sh          # write
#   scripts/agents/sync-agents.sh --check  # exit 1 if anything is stale
#
# A consuming repo that vendors this tree renders its own rosters from the
# vendored canon plus an overlay manifest (extra tools such as a tracker
# MCP, a different fallback model): set AGENTS_CANON to the vendored
# .agents/agents, AGENTS_MANIFEST to the vendored manifest,
# AGENTS_MANIFEST_OVERLAY to the repo's own (merged over it, agent by agent,
# harness by harness), and run from the repo root.
set -euo pipefail
ROOT="$(git rev-parse --show-toplevel)"; cd "$ROOT"
CANON="${AGENTS_CANON:-.agents/agents}"; MANIFEST="${AGENTS_MANIFEST:-.agents/agent-manifest.json}"
check=false; [ "${1:-}" = --check ] && check=true
[ -f "$MANIFEST" ] || { echo "missing $MANIFEST" >&2; exit 2; }
command -v jq >/dev/null || { echo "need jq" >&2; exit 2; }
if [ -n "${AGENTS_MANIFEST_OVERLAY:-}" ]; then
  [ -f "$AGENTS_MANIFEST_OVERLAY" ] || { echo "missing $AGENTS_MANIFEST_OVERLAY" >&2; exit 2; }
  merged="$(mktemp)"; trap 'rm -f "$merged"' EXIT
  jq -s '.[0] * .[1]' "$MANIFEST" "$AGENTS_MANIFEST_OVERLAY" > "$merged"; MANIFEST="$merged"
fi

declare -A DIRS=([claude-code]=.claude/agents [cursor]=.cursor/agents)

render() { # name harness -> stdout
  local src="$CANON/$1.md" inject
  inject="$(jq -r --arg n "$1" --arg h "$2" '.[$n][$h] // {} | to_entries[] | "\(.key): \(.value)"' "$MANIFEST")"
  awk -v name="$1" '
    NR==1 && $0=="---" { infm=1; print; next }
    infm && $0=="---" {
      print "# Generated by scripts/agents/sync-agents.sh from .agents/agents/" name ".md;"
      print "# edit that file and .agents/agent-manifest.json, never this copy."
      while ((getline line < "/dev/stdin") > 0) print line
      infm=0
    }
    { print }' "$src" <<<"$inject"
}

stale=(); tmp="$(mktemp)"; trap 'rm -f "$tmp" "${merged:-}"' EXIT
for src in "$CANON"/*.md; do
  name="$(basename "$src" .md)"
  jq -e --arg n "$name" '.[$n]' "$MANIFEST" >/dev/null || { echo "$CANON/$name.md has no manifest entry" >&2; exit 2; }
  for h in "${!DIRS[@]}"; do
    dst="${DIRS[$h]}/$name.md"
    if jq -e --arg n "$name" --arg h "$h" '.[$n] | has($h)' "$MANIFEST" >/dev/null; then
      render "$name" "$h" > "$tmp"
      cmp -s "$tmp" "$dst" && continue
      stale+=("$dst"); $check && continue
      mkdir -p "$(dirname "$dst")"; cp "$tmp" "$dst"; chmod 644 "$dst"
    elif [ -f "$dst" ] && head -3 "$dst" | grep -q "Generated by scripts/agents/sync-agents.sh"; then
      stale+=("$dst (remove)"); $check && continue
      rm -f "$dst"
    fi
  done
done
for n in $(jq -r 'keys[] | select(startswith("$") | not)' "$MANIFEST"); do [ -f "$CANON/$n.md" ] || { echo "manifest names $n but $CANON/$n.md does not exist" >&2; exit 2; }; done
if $check; then
  [ "${#stale[@]}" -eq 0 ] && exit 0
  printf 'stale agent copy: %s\n' "${stale[@]}" >&2
  echo "run scripts/agents/sync-agents.sh" >&2; exit 1
fi
[ "${#stale[@]}" -eq 0 ] && echo "up to date" || printf 'synced %s\n' "${stale[@]}"
